server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 106.14.184.129:8848
    gateway:
      routes:
        - id: user-service # 路由id，自定义，只要唯一即可
            # uri: http://127.0.0.1:8081 # 路由的目标地址 http就是固定地址
          uri: lb://user-service # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/user/** # 这个是按照路径匹配，只要以/user/开头就符合要求
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
            - Before=2031-04-13T15:14:47.433+08:00[Asia/Shanghai]
#          filters: # 过滤器,只对order请求有效
#            - AddRequestHeader=Truth, Itcast is freaking awesome! # 添加请求头
      default-filters: # 全局过滤项
        - AddRequestHeader=Truth, Itcast is freaking awesome!